# Site settings
title: Our Company Updates
author:
  name: Leonard Williams
  email: leowill01@icloud.com
description: "this is a site about our company."

# Build settings
# remote_theme: jekyll/slate
theme: slate
